[env:bpi-leaf-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.psram_freq = 80m
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi

lib_deps = 
	https://github.com/tttapa/Control-Surface.git#2.1.2
	h2zero/NimBLE-Arduino

build_flags = 
	-D CS_USE_NIMBLE=1
	-DBOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D CORE_DEBUG_LEVEL=0
	-D USB_MANUFACTURER="\"BananaPi\""
	-D USB_PRODUCT="\"MultiFX_Controller\""
	-ffast-math
	-ftree-vectorize
	-fsingle-precision-constant
	-O3