[env:bpi-leaf-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.psram_freq = 80m
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
lib_deps = 
	https://github.com/tttapa/Control-Surface.git#2.1.2
	bodmer/TFT_eSPI@^2.5.43

build_flags = 
	-D CS_USE_NIMBLE=1
	-D CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT=12
	-D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
	-D CONFIG_BT_NIMBLE_ACL_BUF_COUNT=12
	-ffast-math
	-ftree-vectorize
	-DBOARD_HAS_PSRAM
	-D CONFIG_FREERTOS_HZ=100
	-D ARDUINO_USB_MODE=0
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D USB_MANUFACTURER="\"BananaPi\""
	-D USB_PRODUCT="\"MultiFX_Controller\""
	-D CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
	-D CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_64B=y
	-D CONFIG_ESP32S3_INSTRUCTION_CACHE_SIZE_32KB=y
	-I lib/esp-dsp/modules/fft/include
	-I lib/esp-dsp/modules/common/include
	-I lib/esp-dsp/modules/math/include
	-I lib/esp-dsp/modules/wind/include
	-D CONFIG_PM_ENABLE=1
	-D CONFIG_PM_DFS_INIT_AUTO=1
	-fsingle-precision-constant
	-D USER_SETUP_LOADED=1
	-include include/tft_setup.h